server:
  port: 8081



spring:
  data:
    solr:
      host: http://localhost:8080/solr/core1
  mvc:
    static-path-pattern: /static/**

    #配置视图解析器
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///beauty?zeroDateTimeBehavior=convertToNull&amp;characterEncoding=utf-8
    username: root
    password: 666
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      min-idle: 20
      initial-size: 1



  #配置xml形式的mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo